# Generated by Django 3.2.7 on 2021-11-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Surname', models.CharField(max_length=64)),
                ('Event', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
